### ISSUE TITLE
drop validate_options() from hintr_run_model()?

### ISSUE THREAD

**Issue by jeffeaton** [mrc-ide/naomi#175]
@r-ash: Now that the 'validate' button on the model options page is active, can we remove `validate_model()` from `hintr_run_model()`?

https://github.com/mrc-ide/naomi/blob/1ead78db11e98f83c7ae73982cc45943a86384c3/R/run-model.R#L71

**Comment by r-ash** [comment]
We will need to update the progress messages too which is the only thing which is potentially tricky. It shouldn't be too bad though, biggest faff is probably updating tests of the progress messages.

**Comment by jeffeaton** [comment]
This is completed by #181. Closing issue.
